# Generated by Django 4.2.1 on 2023-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('cateGory', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('stockQuantity', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
    ]
